### PR TITLE
Publish Grijjy foundation classes as a package for Delphinus package manager

### PR DESCRIPTION
**Pull request by Pawe1**
💡 **Idea to consider**

Maybe the whole **Delphinus** project (https://github.com/Memnarch/Delphinus) is not so mature but I think it's just really nice tool for Delphi because it can work directly with GitHub (in opposite to GetIt).

**Why?**
 - to spread a word about Your work because IMHO this is a high quality code
 - to be able to add GrijjyFoundation as dependency for other packages.
 - to make download and updates quick & easy

The line with keyword "Delphinus-Support" in readme is needed to find GrijjyFoundation repository via GitHub API.

In case of any questions ask @Memnarch (author of the tool)

~~PS. I have assumed that minimal supported compiler version is 10.2 Tokyo (magic const "32")~~

### CODE REVIEW

**Comment by erikvanbilsen** [comment]
Thanks for the suggestion. We will look into Delphinus before merging this pull request. If we like it, we may offer some of our other repositories as well. BTW, the foundation repository works with 10.1 Berlin as well.

**Comment by Memnarch** [comment]
@erikvanbilsen cool! If you have any questions, don't hesitate to ask me.

**Comment by Pawe1** [comment]
@erikvanbilsen I changed minimum compiler version to 10.1 Berlin in metadata.

**Comment by Memnarch** [comment]
There are two ways to specify the required versions for a package:
Conservative:
Defining strict min/max values(while the max value is the most recent delphi)
Progressive:
When most recent Delphi-Version is supported, just specify the min-version.

I tend to do the later one. But that is up to the packageauthor.

**Pull request merged**
